AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  edge-workshop-apis

  Sample SAM Template for edge-workshop-apis

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  AgentAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: agent_api/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        AgentAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /agent_check
            Method: GET
            TimeoutInMillis: 15000
            RouteSettings:
              ThrottlingBurstLimit: 150
  QSAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: qs_api/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        AgentAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /qs_check
            Method: GET
            TimeoutInMillis: 15000
            RouteSettings:
              ThrottlingBurstLimit: 150

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefaultRouteSettings:
        ThrottlingBurstLimit: 150
      Domain:
        DomainName: edge.api.boaz.cloud
        CertificateArn: arn:aws:acm:us-west-1:762542255826:certificate/c6b0221b-67e1-4b17-8c10-b5fa8cac2721
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z0951163Q47DQWODRJB5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AgentAPI:
    Description: "HTTP API endpoint URL for AgentAPI function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/agent_check"
  QSAPI:
    Description: "HTTP API endpoint URL for QSAPI function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/qs_check?[SOME QUERY STRING]"
  AgentAPIFunction:
    Description: "AgentAPI Lambda Function ARN"
    Value: !GetAtt AgentAPIFunction.Arn
  AgentAPIFunctionIamRole:
    Description: "Implicit IAM Role created for AgentAPI function"
    Value: !GetAtt AgentAPIFunctionRole.Arn
  QSAPIFunction:
    Description: "QSAPI Lambda Function ARN"
    Value: !GetAtt QSAPIFunction.Arn
  QSAPIFunctionIamRole:
    Description: "Implicit IAM Role created for QSAPI function"
    Value: !GetAtt QSAPIFunctionRole.Arn
